name: Build AngularJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install yarn
      run: npm install --global yarn
      
    - name: Build
      run: |
        yarn install
        yarn grunt package

    - name: Test
      run: yarn grunt test:unit
